require "../function"

class Crinja::Tag::For::ForLoop
  include Object

  getter iterator

  @[Crinja::Attribute]
  def length
    # TODO: replace with getter when attributes work with getter
    @length
  end

  @[Crinja::Attribute]
  def index0
    @index0
  end

  @[Crinja::Attribute]
  def revindex0
    @revindex0
  end

  @[Crinja::Attribute]
  def first
    @first
  end

  @[Crinja::Attribute]
  def last
    @last
  end

  # Real Jinja2's `LoopContext` keeps `_before`/`_current`/`_after`
  # bookkeeping (jinja2/runtime.py): `previtem` is the previous item
  # EXCEPT during the first iteration, where it is a genuine Undefined
  # object (so `|default(...)` and `is defined` both work), and
  # `nextitem` returns the lookahead buffer, again as Undefined when the
  # iterable is exhausted. This fork had no such bookkeeping, so
  # previtem/nextitem always resolved to Undefined - the differential
  # harness (real Jinja2 3.1.6's own upstream test suite) rendered
  # `x-0-x|x-1-x|...` where real Jinja2 renders `x-0-1|0-1-2|...`.
  @[Crinja::Attribute]
  def previtem : Value
    if index0 == 0
      Value.new(Undefined.new("there is no previous item"))
    else
      Value.new(@before)
    end
  end

  @[Crinja::Attribute]
  def nextitem : Value
    if (after = @after)
      after
    else
      Value.new(Undefined.new("there is no next item"))
    end
  end

  def crinja_attribute(attr : Value) : Value
    # FIXME: Should be autogenerated by Crinja::Attribute
    # For some reason, the methods array is empty
    value = case attr.to_string
            when "length"
              self.length
            when "index0"
              self.index0
            when "revindex0"
              self.revindex0
            when "first"
              self.first
            when "last"
              self.last
            when "index"
              self.index
            when "revindex"
              self.revindex
            when "cycle"
              self.cycle
            when "previtem"
              self.previtem
            when "nextitem"
              self.nextitem
            when "changed"
              self.changed
            else
              Crinja::Undefined.new(attr.to_s)
            end

    Crinja::Value.new(value)
  end

  @length : Int32 = Int32::MIN
  @revindex0 : Int32 = Int32::MIN
  @before : Value? = nil
  @current : Value? = nil
  @after : Value? = nil
  @changed_method : ChangedMethod? = nil

  def self.new(collection : Value) : self
    raw = collection.raw

    if raw.is_a?(Iterator(Value))
      new(raw)
    else
      new(collection.each, collection.size)
    end
  end

  def initialize(iterator : Iterator(Value), @length : Int32)
    initialize(iterator)

    if length < 2
      @revindex0 = 1
      @last = true
    else
      @revindex0 = length
      @last = false
    end
  end

  def initialize(@iterator : Iterator(Value))
    @index0 = -1
    @first = true
    @last = false
  end

  def each(&)
    value = iterator.next

    while true
      if value.is_a?(Iterator::Stop)
        break
      else
        @index0 += 1
        @revindex0 -= 1 unless @length == Int32::MIN

        next_value = iterator.next
        if next_value.is_a?(Iterator::Stop)
          @last = true
          @length = index
          @revindex0 = 0
          @after = nil
        else
          # The lookahead already fetched for `last` doubles as
          # `nextitem`'s buffer, mirroring real Jinja2's `_after` cache
          # which `__next__` consumes instead of re-reading the iterator.
          @after = next_value
        end

        @before = @current
        @current = value

        yield value.as(Value)

        value = next_value

        @first = false
      end
    end
  end

  @[Crinja::Attribute]
  def index
    index0 + 1
  end

  @[Crinja::Attribute]
  def revindex
    revindex0 == Int32::MIN ? Int32::MIN : revindex0 + 1
  end

  @[Crinja::Attribute]
  def cycle
    CycleMethod.new(self)
  end

  # Memoized so the per-loop `_last_changed_value` state (real Jinja2
  # stores the previous call's argument tuple on the LoopContext itself)
  # survives repeated `loop.changed(...)` attribute lookups within one
  # iteration - a fresh instance per lookup would always report True.
  @[Crinja::Attribute]
  def changed : Value
    Value.new(@changed_method ||= ChangedMethod.new(self))
  end

  class ChangedMethod
    include Callable

    @last : Array(Value)?

    def initialize(@loop : ForLoop)
      @last = nil
    end

    # Real Jinja2's `LoopContext.changed(*value)` compares the WHOLE
    # argument tuple against the previous call's tuple (True on the
    # first call): `if self._last_changed_value != value`. Comparing
    # only the single argument would collapse
    # `[null, null, 1, 2, 2, ...]|loop.changed(item)` to True,False,True...
    # instead of the real True,False,True,True,False,...
    def call(arguments : Arguments) : Value
      args = arguments.varargs
      last = @last

      if last.nil? || last != args
        @last = args
        Value.new(true)
      else
        Value.new(false)
      end
    end
  end

  class CycleMethod
    include Callable

    def initialize(@loop : ForLoop)
    end

    def call(arguments : Arguments) : Value
      arguments.varargs[@loop.index0 % arguments.varargs.size]
    end
  end

  class Recursive < ForLoop
    include Callable

    setter depth0 : Int32 = 0

    def crinja_attribute(attr : Value) : Value
      # FIXME: Should be autogenerated by Crinja::Attribute
      # For some reason, the methods array is empty
      value = case attr.to_string
              when "depth"
                Crinja::Value.new(self.depth)
              when "depth0"
                Crinja::Value.new(self.depth0)
              else
                super(attr)
              end
      value
    end

    @[Crinja::Attribute]
    def depth0
      @depth0
    end

    @loop_runner : Crinja::Tag::For::Runner

    def self.new(loop_runner, collection : Value) : self
      raw = collection.raw
      if raw.is_a?(Iterator(Value))
        new(loop_runner, raw)
      else
        new(loop_runner, collection.each, collection.size)
      end
    end

    def initialize(@loop_runner, iterator : Iterator(Value), length : Int32)
      super(iterator, length)
    end

    def initialize(@loop_runner, iterator : Iterator(Value))
      super(iterator)
    end

    def call(arguments : Arguments)
      sub_iterator = arguments.varargs.first

      sub_loop = self.class.new(@loop_runner, sub_iterator)
      sub_loop.depth0 = self.depth

      SafeString.build do |io|
        io << @loop_runner.run_loop(sub_loop).value
      end
    end

    @[Crinja::Attribute]
    def depth
      depth0 + 1
    end
  end
end
